services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: course-plataform
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer : 
    image: adminer
    restart : always
    ports : 
      - 8080:8080
        
volumes:
  postgres_data:
